name: Verificador Diário de Assinaturas

on:
  schedule:
    # Roda todo dia às 12:00 UTC (9:00 da manhã no horário de Recife)
    - cron: '0 12 * * *'
  workflow_dispatch: # Permite rodar manualmente pela interface do GitHub

jobs:
  verificar:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Baixar o código do repositório
        uses: actions/checkout@v4

      - name: 2. Configurar o ambiente Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: 3. Instalar as dependências do projeto
        run: pip install -r requirements.txt

      - name: 4. Executar o script de verificação
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          EMAIL_ADMIN: ${{ secrets.EMAIL_ADMIN }}
        run: python verificador_diario.py